# Generated by Django 3.2 on 2021-06-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210517_2251'),
        ('project', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to='user.user', verbose_name='Автор'),
        ),
    ]
