# Generated by Django 3.2 on 2021-06-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210517_2251'),
        ('project', '0003_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teg',
            field=models.ManyToManyField(related_name='tags', to='user.Skill', verbose_name='Теги'),
        ),
    ]
