# Generated by Django 3.2 on 2021-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210517_2251'),
        ('project', '0004_project_teg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teg',
            field=models.ManyToManyField(default=None, related_name='tags', to='user.Skill', verbose_name='Теги'),
        ),
    ]
