# Generated by Django 3.2 on 2021-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210624_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_in_search',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Находится в поиске'),
        ),
    ]
