# Generated by Django 3.2 on 2021-05-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='user_skills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.skill', verbose_name='Навыки'),
            preserve_default=False,
        ),
    ]
