# Generated by Django 3.2 on 2021-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_skill_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='FFF', max_length=50, unique=True, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
