# Generated by Django 3.2 on 2021-05-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользователь'),
        ),
    ]
