# Generated by Django 3.2 on 2021-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_skill_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
