# Generated by Django 3.2 on 2021-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_activate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activation',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
